// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consents.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertConsent = `-- name: InsertConsent :exec
INSERT INTO user_consents (id, user_id, policy_type, version, service_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertConsentParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	PolicyType string
	Version    string
	ServiceID  pgtype.Text
}

func (q *Queries) InsertConsent(ctx context.Context, arg InsertConsentParams) error {
	_, err := q.db.Exec(ctx, insertConsent,
		arg.ID,
		arg.UserID,
		arg.PolicyType,
		arg.Version,
		arg.ServiceID,
	)
	return err
}

const listConsentsByUserID = `-- name: ListConsentsByUserID :many
SELECT id, user_id, policy_type, version, service_id, consented_at FROM user_consents
WHERE user_id = $1
ORDER BY consented_at ASC
`

func (q *Queries) ListConsentsByUserID(ctx context.Context, userID pgtype.UUID) ([]UserConsent, error) {
	rows, err := q.db.Query(ctx, listConsentsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserConsent
	for rows.Next() {
		var i UserConsent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PolicyType,
			&i.Version,
			&i.ServiceID,
			&i.ConsentedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
