// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :exec
INSERT INTO user_project_memberships (user_id, client_id)
VALUES ($1, $2)
ON CONFLICT (user_id, client_id) DO NOTHING
`

type CreateMembershipParams struct {
	UserID   pgtype.UUID
	ClientID pgtype.UUID
}

func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) error {
	_, err := q.db.Exec(ctx, createMembership, arg.UserID, arg.ClientID)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT user_id, client_id, joined_at FROM user_project_memberships
WHERE user_id = $1 AND client_id = $2
`

type GetMembershipParams struct {
	UserID   pgtype.UUID
	ClientID pgtype.UUID
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (UserProjectMembership, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.ClientID)
	var i UserProjectMembership
	err := row.Scan(&i.UserID, &i.ClientID, &i.JoinedAt)
	return i, err
}
