// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OauthClient struct {
	ClientID            pgtype.UUID
	Name                string
	LogoUrl             pgtype.Text
	FaviconUrl          pgtype.Text
	GradientFrom        string
	GradientTo          string
	TextDark            pgtype.Bool
	AllowedRedirectUris []string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ClientID  pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserConsent struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	PolicyType  string
	Version     string
	ServiceID   pgtype.Text
	ConsentedAt pgtype.Timestamptz
}

type UserOauthAccount struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type UserProjectMembership struct {
	UserID   pgtype.UUID
	ClientID pgtype.UUID
	JoinedAt pgtype.Timestamptz
}
