// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_clients.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllowedRedirectURIs = `-- name: GetAllowedRedirectURIs :one
SELECT allowed_redirect_uris FROM oauth_clients
WHERE client_id = $1
`

func (q *Queries) GetAllowedRedirectURIs(ctx context.Context, clientID pgtype.UUID) ([]string, error) {
	row := q.db.QueryRow(ctx, getAllowedRedirectURIs, clientID)
	var allowed_redirect_uris []string
	err := row.Scan(&allowed_redirect_uris)
	return allowed_redirect_uris, err
}

const getOAuthClientByID = `-- name: GetOAuthClientByID :one
SELECT client_id, name, logo_url, favicon_url, gradient_from, gradient_to, text_dark, allowed_redirect_uris, created_at, updated_at FROM oauth_clients
WHERE client_id = $1
`

func (q *Queries) GetOAuthClientByID(ctx context.Context, clientID pgtype.UUID) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.Name,
		&i.LogoUrl,
		&i.FaviconUrl,
		&i.GradientFrom,
		&i.GradientTo,
		&i.TextDark,
		&i.AllowedRedirectUris,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
