// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth_accounts.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOAuthAccountByProvider = `-- name: GetOAuthAccountByProvider :one
SELECT id, user_id, provider, provider_user_id, email, created_at FROM user_oauth_accounts
WHERE provider = $1 AND provider_user_id = $2
`

type GetOAuthAccountByProviderParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetOAuthAccountByProvider(ctx context.Context, arg GetOAuthAccountByProviderParams) (UserOauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccountByProvider, arg.Provider, arg.ProviderUserID)
	var i UserOauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const upsertOAuthAccount = `-- name: UpsertOAuthAccount :one
INSERT INTO user_oauth_accounts (id, user_id, provider, provider_user_id, email)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider, provider_user_id)
DO UPDATE SET email = EXCLUDED.email
RETURNING id, user_id, provider, provider_user_id, email, created_at
`

type UpsertOAuthAccountParams struct {
	ID             pgtype.UUID
	UserID         pgtype.UUID
	Provider       string
	ProviderUserID string
	Email          pgtype.Text
}

func (q *Queries) UpsertOAuthAccount(ctx context.Context, arg UpsertOAuthAccountParams) (UserOauthAccount, error) {
	row := q.db.QueryRow(ctx, upsertOAuthAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
	)
	var i UserOauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
