// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (id, user_id, client_id, token_hash, expires_at, user_agent)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, client_id, token_hash, expires_at, revoked_at, user_agent, created_at
`

type CreateRefreshTokenParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ClientID  pgtype.UUID
	TokenHash string
	ExpiresAt pgtype.Timestamptz
	UserAgent pgtype.Text
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.ClientID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, client_id, token_hash, expires_at, revoked_at, user_agent, created_at FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.CreatedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
